---
# tasks file for roles/create_ec2instance
- name: Criando uma nova VPC 
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ cidr_block }}"
    region: "{{ region }}"
  register: vpc

- name: Criando uma nova Subnet
  amazon.aws.ec2_vpc_subnet:
    cidr: "{{ cidr }}"
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc.id }}"
  register: subnet

- name: Criando um Grupo de Seguranca AWS  
  amazon.aws.ec2_security_group:
    name: "Ansible-Test-Security-Group"
    description: "Ansible-Testing"
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
        - 80
        - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: "allow all on port 80"
  register: security_group

- ansible.builtin.debug:
    var: security_group.group_id

- ansible.builtin.debug:
    var: subnet.subnet.id

- name: "Criando uma instancia EC2 - {{ ec2_instance_name }}"
  amazon.aws.ec2_instance:
    name: "{{ ec2_instance_name }}"
    key_name: "{{ key_name }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    instance_type: "{{ instance_type }}"
    security_group: "{{ security_group.group_id  }}"
    count: 1
    wait: yes
    aws_region: "{{ region }}"
    network:
      assign_public_ip: true
    image_id: "{{ ami }}"
  register: ec2_vm
 
- name: Criando um grupo de inventario em tempo de execucao
  ansible.builtin.add_host:
    name: "{{ ec2_vm['tags']['Name'] }}"
#    ansible_user: "{{ ec2_username }}"
#    ansible_host: "{{ ec2_vm['instances']['public_ip_address'] }}"
    ansible_host: "{{ ec2_vm['private_ip_address'] }}" 
    private_ip: "{{ ec2_vm['private_ip_address'] }}"
    instance_name: "{{ ec2_vm['tags']['Name'] }}" 
    groups:
      - ec2_new_instances
