---
- name: Criando instancia EC2 
  hosts: localhost
  roles:
    - create_ec2instance 

# O grupo de inventario "ec2_new_instances" é gerado em tempo de execução no play "Criando instancia EC2"
- name: Configurando a nova instancia EC2
  hosts: ec2_new_instances
  become: true
  roles:
    - configure_ec2instance
...
