---
# tasks file for roles/configure_ec2instance

- name: Aguardando reposta SSH do novo servidor (Max 600s)
  ansible.builtin.wait_for_connection:

- name: Config SManager - sshd_config
  ansible.builtin.template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: restart sshd

- name: Pacotes SManager 
  ansible.builtin.package:
    name:
      - tmux
      - chrony
      - tuned
      - bind-utils

- name: Criando persistencia de servicos - boot
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - tuned
    - chronyd 

- name: Configurando Time Zone America/Sao_Paulo
  community.general.timezone:
    name: America/Sao_Paulo 

- name: Configurando pool de servidores NTP Brasileiros
  ansible.builtin.template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf 
    owner: root
    group: root
    mode: 0644
  notify: restart chronyd 

- name: Tuning - Aplicando perfil recomendado para VMs
  ansible.builtin.command: tuned-adm profile virtual-guest
