---
# tasks file for roles/configure_ec2instance

- name: Aguardando reposta SSH do novo servidor (Max 600s)
  ansible.builtin.wait_for_connection:

- name: Configuracao padrao SManager - sshd_config
  ansible.builtin.template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
