---
# handlers file for roles/configure_ec2instance
- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: restart chronyd 
  ansible.builtin.service:
    name: chronyd 
    state: restarted
